### ISSUE TITLE
Unable to update -f

### ISSUE THREAD

**Issue by zhaiyuzhen** [clonos/control-pane#24]
Hellow,
      When I add the ClonOS-pkg.ircdriven.net repos and try update -f,it fails.
root@node67:~ # uname -a
FreeBSD node67 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64
root@node67:~ # pkg update -f
Updating ClonOS-pkg.ircdriven.net repository catalogue...
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
pkg: https://pkg.ircdriven.net/packages/12amd64-clonos//meta.txz: Authentication error
repository ClonOS-pkg.ircdriven.net has no meta file, using default settings
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
pkg: https://pkg.ircdriven.net/packages/12amd64-clonos//packagesite.txz: Authentication error
Unable to update repository ClonOS-pkg.ircdriven.net
Updating FreeBSD repository catalogue...
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
pkg: https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD:12:amd64/latest/meta.txz: Authentication error
repository FreeBSD has no meta file, using default settings
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
pkg: https://mirrors.ustc.edu.cn/freebsd-pkg/FreeBSD:12:amd64/latest/packagesite.txz: Authentication error
Unable to update repository FreeBSD
Error updating repositories!

**Comment by zhaiyuzhen** [comment]
sorry,my fault. It's because another repos.
When I installed ca_root_nss-3.47,it shows:
root@node67:~ # pkg update -f
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01    
Fetching packagesite.txz: 100%    6 MiB   6.6MB/s    00:01    
Processing entries: 100%
FreeBSD repository update completed. 32617 packages processed.
Updating ClonOS-pkg.ircdriven.net repository catalogue...
Certificate verification failed for /CN=pkg.ircdriven.net
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /CN=pkg.ircdriven.net
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /CN=pkg.ircdriven.net
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
pkg: https://pkg.ircdriven.net/packages/12amd64-clonos//meta.txz: Authentication error
repository ClonOS-pkg.ircdriven.net has no meta file, using default settings
Certificate verification failed for /CN=pkg.ircdriven.net
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /CN=pkg.ircdriven.net
34375614464:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:

**Comment by zhaiyuzhen** [comment]
I can install via clonos-19.09-release.img, the issues can be closed.

**Comment by cdumke** [comment]
For solution refer to [https://forums.freebsd.org/threads/freebsd-as-a-host-with-bhyve.60561/](https://forums.freebsd.org/threads/freebsd-as-a-host-with-bhyve.60561/)

Summary steps:

1. deactivate Clonos repo in file "/usr/local/etc/pkg/repos/clonos-pkg.ircdriven.net.conf":
`ClonOS-pkg.ircdriven.net: {`
`        url: "https://pkg.ircdriven.net/packages/12amd64-clonos/",`
`        mirror_type: "none",`
**`        enabled: no`**
`}`
2. install "ca_root_nss":
`pkg install ca_root_nss`
3. activate Clonos repo in file "/usr/local/etc/pkg/repos/clonos-pkg.ircdriven.net.conf":
`ClonOS-pkg.ircdriven.net: {`
`        url: "https://pkg.ircdriven.net/packages/12amd64-clonos/",`
`        mirror_type: "none",`
**`        enabled: yes`**
`}`
4. update repos:
`pkg update -f`
5. install clonos:
`pkg install clonos`
