### ISSUE TITLE
Installing ClonOS/CBSD WEB UI via PKG on FreeBSD 12

### ISSUE THREAD

**Issue by xplitz27** [clonos/control-pane#26]
After enabling the repository on `/usr/local/etc/pkg/repos/clonos-pkg.ircdriven.net.conf`
with
`ClonOS-pkg.ircdriven.net: {
        url: "https://pkg.ircdriven.net/packages/12amd64-clonos/",
        mirror_type: "none",
        enabled: yes
}`

I ran `pkg update -f
pkg install clonos`

it returns with an error
`pkg: https://pkg.ircdriven.net/packages/12amd64-clonos/All/clonos-19.09.txz: Not Found`

anyone know what to do? Thank you!

**Comment by xplitz27** [comment]
I checked the url, it seems that clonos-19.09.txz is not there...

**Comment by savichev** [comment]
https://jenkins.ircdriven.net/job/Update%20clonos%20packages./
![image](https://user-images.githubusercontent.com/12516628/77507246-de74e880-6e89-11ea-999c-33d79191c306.png)

**Comment by y2kbadbug** [comment]
I barely found this issue.  It's kind of old, but I am the owner of that mirror.  I honestly did not realize people used this and hadn't maintained it.  I will work this week to bringing it up to date and getting it going again in case anyone else needs to use it.  I will ensure there are builds for both FreeBSD 12 and 13.

**Comment by olevole** [comment]
@y2kbadbug Your mirrors ( https://clonos.ca.ircdriven.net/iso/ https://clonos.us.ircdriven.net/iso/ )  still used in all the **CBSD** profiles as a mirror. I don’t know how much they are in the current state and their statistics.

As for ClonOS+Jenkins, I think now it's irrelevant: the project goes to the new build script. Experimental and official repository is pkg+http://clonos-pkg.convectix.com/${ABI}/latest:
```
ClonOS-latest: {
  url: "pkg+http://clonos-pkg.convectix.com/${ABI}/latest",
  mirror_type: "srv",
  signature_type: "NONE",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes,
  conservative_upgrade: no,
  priority: 100
}
```

Work on the ClonOS project moves very slowly from the absence of a web developer (I mainly deal with backend/CBSD) and the lack of equipment/hosting. Therefore, I do not know when the process over the new release will be completed.
But when this happens, we can connect your mirrors for PKG repo.

**Comment by olevole** [comment]
FreeBSD 12 too old for now, we go towards the official repository for FreeBSD 13+ ^^
