### ISSUE TITLE
Fresh install cant login admin / admin Error! user not found

### ISSUE THREAD

**Issue by outbackdingo** [clonos/control-pane#51]
i did a fresh install of clonOS following the installation_on_freebsd on 13.0-RELEASE and get a web ui but cannot login

![image](https://user-images.githubusercontent.com/52370034/180589772-d92cd7da-24e8-4284-8dd7-968f4cd07496.png)

**Comment by bozhinov** [comment]
I see you pushing commits. so you must have figured it out ?

**Comment by outbackdingo** [comment]
Yupp past there!

**Comment by olevole** [comment]
Just for info: to reset password:
```
rm -f /var/db/clonos/clonos.sqlite /var/db/clonos/salt
cbsd clonosdb
```
