### ISSUE TITLE
initforms.sh: No such file or directory

### ISSUE THREAD

**Issue by outbackdingo** [clonos/control-pane#52]
sh /usr/local/cbsd/modules/clonos_database/initforms.sh
sh: cannot open /usr/local/cbsd/modules/clonos_database/initforms.sh: No such file or directory

**Comment by olevole** [comment]
clonos_database was moved to clonosdb CBSD module, according to installation docs:
```
cbsd module mode=install clonosdb
```

make sure ~cbsd/etc/modules.conf has a line
```
clonosdb.d
```

init CBSD after adding new module and re-run db init:
```
cbsd initenv
cbsd clonosdb
```
