### ISSUE TITLE
clonos repo has been inaccessible for a long time

### ISSUE THREAD

**Issue by derzahla** [clonos/control-pane#64]
Hi, Ive been using the latest clonos dev image for the past few months and  Im enjoying quite a bit,   however I havent been able to get  a vallid response from the repo for many weeks now.    trying to run a 'pkg update' fails with the repo enabled:

```
# pkg update
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating ClonOS-latest repository catalogue...
pkg: No SRV record found for the repo 'ClonOS-latest'
pkg: An error occured while fetching package
pkg: packagesite URL error for pkg+http://clonos-pkg.convectix.com/FreeBSD:13:amd64/latest/meta.txz -- pkg+:// implies SRV mirror type
repository ClonOS-latest has no meta file, using default settings
pkg: packagesite URL error for pkg+http://clonos-pkg.convectix.com/FreeBSD:13:amd64/latest/packagesite.pkg -- pkg+:// implies SRV mirror type
pkg: packagesite URL error for pkg+http://clonos-pkg.convectix.com/FreeBSD:13:amd64/latest/packagesite.txz -- pkg+:// implies SRV mirror type
Unable to update repository ClonOS-latest
Error updating repositories!

```

Is it going to be brought back online or is there a replacement? Or I did I somehow break things on my side?  I've searched on github, clonos site and all over but do not see any updates posted.  

thanks

**Comment by olevole** [comment]
We are slowly moving to FreeBSD 14.0 ( according to [FreeBSD release page](https://www.freebsd.org/releases/14.0R/schedule/) the release will be in October) due to important bhyve fixes regarding stability.

Next development build will use 'pkg+http://clonos-pkg.convectix.com/FreeBSD:**14**:amd64' ( of course, the base and kernel migrate to 14.0 )

**Comment by derzahla** [comment]
oh ok, got it.  Thanks for the reply.  Are changes like this just posted only in the telegram channel?  Is there a path to do a binary upgrade to the latest dev build from the 13.2 based image I installed or just am i stuck with  the standard FreeBSD "recompile all the things" method? :)

**Comment by olevole** [comment]
Sorry for the delay. From an old installation, updating is not possible in a simple way ;(
One of the new improvements in the upcoming release --  is the ability to update.
Starting from the 23.10+ version, ClonOS has been swithed to [base-in-pkg method](https://wiki.freebsd.org/PkgBase) and the project infrastructure supports for updates.

![image](https://github.com/clonos/control-pane/assets/926409/64245c21-95f3-4b23-aad4-a49ed5406306)
