### ISSUE TITLE
Import files for French translation from clone.

### ISSUE THREAD

**Issue by gil-andre** [clonos/control-pane#68]
The files `fr.js` and `fr.php` are attached to this message.
[fr_trad.zip](https://github.com/user-attachments/files/15937989/fr_trad.zip)

**Comment by gil-andre** [comment]
hope this helps!

**Comment by gyptazy** [comment]
Hey @gil-andre,

thanks for your work, time and efforts! I created a PR (#69) based on this like written on the Fediverse and set you as sponsored-by line since you did not create a PR.

Cheers,
gyptazy
